### ISSUE TITLE
Error log: Failed to load model

### ISSUE THREAD

**Issue by MrGreenTea** [Flomik10002/DelightfulCreatorsFabric#11]
When using this mod I get quite some error spam in my logs that all look something like this.

It does not happen for any other mod and happens with a clean install with these mods:

- Fabric API `0.90.4+1.20.1`
- Delightful Creators `1.1.8`
- Create `0.5.1-d-build.1161+mc1.20.1`
- Farmer's Delight `1.20.1-1.4.2`

```
[16:54:13] [Worker-ResourceReload-13/ERROR]: Failed to load model delightfulcreators:models/block/vegetable_soup_block.json
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
	at java.lang.String.charAt(String.java:1515) ~[?:?]
	at net.minecraft.class_793.method_3439(class_793.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.class_793$class_795.method_24079(class_793.java:355) ~[client-intermediary.jar:?]
	at net.minecraft.class_793$class_795.method_3448(class_793.java:347) ~[client-intermediary.jar:?]
	at net.minecraft.class_793$class_795.method_3451(class_793.java:308) ~[client-intermediary.jar:?]
	at net.minecraft.class_793$class_795.deserialize(class_793.java:300) ~[client-intermediary.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:524) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15276(class_3518.java:581) ~[client-intermediary.jar:?]
	at net.minecraft.class_793.method_3437(class_793.java:86) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45898(class_1092.java:105) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

It seems non critical but the spam inside the error logs causes some serious errors to become harder to spot. Would be great if you could do something about it.

**Comment by napmouse** [comment]
+1 on this. Doesn't cause any crashes as far as I can tell but it does spam the logs pretty excessively.

**Comment by PaulRV0709** [comment]
I get the same kind of log spam:
![image](https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/82379138/5c404e04-4662-4fc4-912a-20f4e83850d2)

**Comment by fionera** [comment]
Sadly still an issue

**Comment by NextRaven10** [comment]
This is still an issue :/
